const products = [
  {
    id: 1,
    title: "Kimchi pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/pancake1.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "Chocolate pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/pancake2.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 3,
    title: "Ube pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/pancake3.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 4,
    title: "Spelt pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/pancake4.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 5,
    title: "Blueberry pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/pancake5.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 6,
    title: "Buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/pancake6.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 7,
    title: "Japanese Soufle pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/pancake7.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 8,
    title: "Mini-Butter pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/pancake8.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 9,
    title: "American pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/pancake9.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 10,
    title: "Chocolate Jaffa pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/pancake10.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
];
window.addEventListener("DOMContentLoaded", function () {
  console.log("Hello world");
});
